# Generated by Django 4.0.4 on 2022-04-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_prettynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
        ),
    ]
